inherit_from: configs/base.yaml

experiment:
  name: visa_winclip_1116_k0
  description: "WinCLIP baseline on VisA"
  output_root: results/visa/winclip

data:
  dataset: visa
  root: data/visa
  split_type: 1cls
  split_csv: data/visa/split_csv/1cls.csv
  categories:
    [
      #"candle",
      # "capsules",
      # "cashew",
      #"chewinggum",
      # "fryum",
      # "macaroni1",
      # "macaroni2",
      # "pcb1",
      "pcb2",
      # "pcb3",
      # "pcb4",
      # "pipe_fryum",
    ]
  loader:
    train_split: train
    test_split: test
    k_shot: 0
    test_file_numbers: [4] 
  batch_size: 4

model:
  name: winclip
  device: cuda
  backbone: ViT-B-16-plus-240
  pretrained_dataset: laion400m_e32
  scales: [2, 3]
  precision: fp16
  img_resize: 240
  img_cropsize: 240
  resolution: 400
  k_shot: 0
  prompt_template: winclip_default
  normalize_score_maps: true

evaluation:
  metrics:
    thresholds:
      image: 100
      pixel: 200
    pro:
      max_fpr: 0.3
      num_thresholds: 200
  latency:
    warmup_iters: 1
    measure_iters: 1
    throughput_num_passes: 1  # Throughput 측정 횟수 (기본값: 1000)
    gpu_memory_num_iters: 1  # GPU 메모리 측정 횟수 (기본값: 1000)

visualization:
  num_examples: 12
  cmap: jet
  save_overlay: true
  overlay_alpha: 0.5

logging:
  log_dir: results/visa/winclip/logs

